use_frameworks!

platform :ios, '8.0'

target 'BTTransition_Example' do
  pod 'BTTransition', :path => '../'
#  pod 'MLeaksFinder'


  target 'BTTransition_Tests' do
    inherit! :search_paths

    
  end
end
